### ISSUE TITLE
wget doesn't work behind http proxy

### ISSUE THREAD

**Issue by baizebing** [NobuoTsukamoto/meta-tensorflow-lite#10]
Cannot do configure in my company's network because wget doesn't work behind the http proxy even if I set http_proxy & https_proxy in my environment. To fix this issue, I temporarily write the wget config ~/.wgetrc :
use_proxy = on
http_proxy = xxxxxxx
https_proxy = xxxxxx

I think this should be fixed because those auto-script should not overwrite the local environment variable, which is quite confusing for other app work properly.

**Comment by NobuoTsukamoto** [comment]
As you can see on the YOCTO wiki.
https://wiki.yoctoproject.org/wiki/Working_Behind_a_Network_Proxy
```
1. Environment variables and configuration files - this is the traditional and least intrusive option but involves a number of steps and it can fail in some situations.
2. Chameleonsocks - this is Redsocks auto-configured in a docker container, the Yocto team's favorite option. If in doubt, go with this option.
```
The Chameleonsocks project is archived and I'm not sure if it works.
Even if support the meta-tensorflow-lite recipe, the same problem will occur with other recipes. For this reason, I think it's better to modify the .wgetrc. If it is affected by other apps, why not build it on Docker?
