### ISSUE TITLE
recipes-tools may not fit as well as recipes-framework

### ISSUE THREAD

**Issue by chadrockey** [NobuoTsukamoto/meta-tensorflow-lite#107]
Just a minor observation when I was making a bbappend and noticed that recipes-tools may not be a widely used classification.  Most libraries are under recipes-devtools and the upstream tensorflow is under recipes-framework.

https://git.yoctoproject.org/meta-tensorflow/tree/recipes-framework/tensorflow

**Comment by chadrockey** [comment]
Sorry, when I reread this, I feel like I didn't communicate my core question clearly.  Upstream tensorflow includes things like tensorboard and estimators in the recipes-framework with the rest.

And as recipes-tools may not be widely used and  recipes-utils may be another possible home for the benchmarking tool.

**Comment by NobuoTsukamoto** [comment]
As you point out, `recipes-utils` seems better than `recipes-tools`.

**Comment by NobuoTsukamoto** [comment]
Fixed in PR #110. Closes.
