### ISSUE TITLE
[Feat Request] Add warrior support...

### ISSUE THREAD

**Issue by madscientist42** [NobuoTsukamoto/meta-tensorflow-lite#3]
Seems to build/work correctly for Warrior (I know...can't exactly move one of my targets (yet!) to Dunfell unfortunately), so you might want to add that in the config...

**Comment by NobuoTsukamoto** [comment]
Thank you for the report.

Added Warrior to the target.
"Gatesgarth" cannot be added to the target because an error occurs when creating pip pakege.

Close the issue. If you have any problems, please open it again.
