### ISSUE TITLE
[kirkstone] libtensorflowlite_c.so not generated

### ISSUE THREAD

**Issue by uid03055** [NobuoTsukamoto/meta-tensorflow-lite#47]
Building the recipe for a Raspberry Pi4, i've got installed libtensorflowlite.so but not  libtensorflowlite_c.so nor c_api.h. How can i make it work?

**Comment by NobuoTsukamoto** [comment]
There is currently no recipe to build the TensorFlow Lite C library (libtensorflowlite_c.so). A recipe needs to be added.

Does your application require libtensorflowlite_c.so?
(pull requests are welcome)

**Comment by uid03055** [comment]
Yes, I need to build a cmake project, which needs the  libtensorflowlite_c.so. Workaroud: seperate recipe, which shifts the lib to /usr/lib or manual copying via scp.

**Comment by NobuoTsukamoto** [comment]
Added recipe for `libtensorflow-lite-c`. #48 
Please comment if you have any problems.

**Comment by uid03055** [comment]
Thank you
