### ISSUE TITLE
Bazel recipe compile issue

### ISSUE THREAD

**Issue by nandra** [NobuoTsukamoto/meta-tensorflow-lite#5]
Hi,

I'm trying to compile pycoral library which is using bazel build tool. I'm using python3-tflite from this layer also. When trying to build bazel-native recipe it fails in compilation phase. I also check and bazel is not used anywhere? I tried to use bazel-native 0.21 from mea-tensorflow but this one seems to be old. Thanks.

**Comment by NobuoTsukamoto** [comment]
Bazel is not used. Not used to build tensorflow-lite.
It's because of the libedgetpu build, but the bazel build doesn't work.
I think it's best to download the release binaries.

**Comment by nandra** [comment]
I have libedgetpu from meta-coral where it works fine. BTW bazel 3.7.1 from meta-tensorflow can be build but I cannot compile pycoral (need to add custom yocto bazel toolchain similar as done for tensorflow package). Thanks.
