### ISSUE TITLE
libedgetpu not working on raspberrypi4

### ISSUE THREAD

**Issue by 7216nat** [NobuoTsukamoto/meta-tensorflow-lite#63]
Trying to reproduce the [# example-object-tracker](https://github.com/google-coral/example-object-tracker/tree/master) on a raspberrypi4 based on this layer...

And the problem that I'm facing right now is that I have found the similar issue that have already mentioned in [this](https://github.com/google-coral/libedgetpu/issues/28#issuecomment-1161605030):

> OSError: /usr/lib/libedgetpu.so.1: undefined symbol: _ZN4absl19str_format_internal13FormatArgImpl8DispatchIPKcEEbNS2_4DataENS1_24FormatConversionSpecImplEPv 
Exception ignored in: <function Delegate.__del__ at 0x7fedbacb0>
Traceback (most recent call last):
   File "/usr/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 118, in __del__
        if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'

Since there is no example of delegating to a edgeTPU, and those *.so are present under /usr/lib/ for sure, I just don`t know what am I doing wrong? 

I am building with kirkstone branch, customized with libedgeTPU updates.

**Comment by 7216nat** [comment]
Closing this issue, I have already solved it.

In case anyone finds themselves in the same situation, for me the problem was no dynamic linking during the libedgetpu's compilation.

**Comment by NobuoTsukamoto** [comment]
Sorry for the late reply.
You say you've already solved it, but I'm guessing that there was probably a problem with the order of the libedgetpu compile options.

I think that it is the contents of the following patch file of the main branch.
- https://github.com/NobuoTsukamoto/meta-tensorflow-lite/blob/e319b761c25ac00f2575ddc5404be1cfa846115f/recipes-framework/coral/files/001-libedgetpu_makefile.patch#L76-L77
