### ISSUE TITLE
Question: is `tensorflow-lite` `2.12.0` supported under `dunfell`?

### ISSUE THREAD

**Issue by BMMevius** [NobuoTsukamoto/meta-tensorflow-lite#75]
While looking through the repository, I was not able to find any support matrix for the embedded version and the TFLite version. So, I was wondering if it is possible to support TFLite under `dunfell`, because that is what I need. If this is not explicitly unsupported, I'm happy to contribute.

**Comment by NobuoTsukamoto** [comment]
The versions supported by dunfell are as follows.
- https://github.com/NobuoTsukamoto/meta-tensorflow-lite/tree/dunfell/recipes-framework/tensorflow-lite
  - 2.3.4
  - 2.4.4
  - 2.5.3
  - 2.6.5
  - 2.7.4
  - 2.8.4

To maintain compatibility, all other than revisions are fixed. For this reason, dunfell does not plan to support versions 2.9 or higher. It may be possible to change `LAYERSERIES_COMPAT_meta-tensorflow-lite` from `mickledore` to `dunfell`, but I have not done so.

I think a version support matrix is a good idea. It's necessary for the README.

**Comment by NobuoTsukamoto** [comment]
@BMMevius -san
I've added the supported versions to the README.
If you need anything else, please send me a pull request.
