### ISSUE TITLE
Build Tensorflow lite on yocto thud

### ISSUE THREAD

**Issue by Kirollos-Henry** [NobuoTsukamoto/meta-tensorflow-lite#9]
Hello all,

I am using arago ti distribution on TDA2Px-EVM and I was able to build the file system and created custom layers to build and install new packages required for some python packages and also added meta-scipy layer.
When I am trying to add meta-tensorflow-lite layer I always gets that error 

"**ERROR: Layer meta-tensorflow-lite is not compatible with the core layer which only supports these series: thud**".

The Arago project of Texas instruments that is compatible with my board is based on thud so is there anyway to build and install tensorflow lite on the that arago project base on thud.

Thanks in Advance.

Best Regards,
Kirollos Henry

**Comment by NobuoTsukamoto** [comment]
`thud` is not included in the confirmed version of meta-tensorflow-lite.
The version ([LAYERSERIES_COMPAT](https://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#var-LAYERSERIES_COMPAT)) is below.
- https://github.com/NobuoTsukamoto/meta-tensorflow-lite/blob/master/conf/layer.conf#L13

Perhaps adding `thud` to the list will allow the build.

**Comment by KirollosTadros** [comment]
thanks for your reply.

I have already noticed that and I already did this before, but I have got an error that "python3-wheel-native" is not provided.

I think this is native in the other distributions or do you have any idea to add and build it.

Thank you in advance,

Best Regards,
Kirollos Henry

**Comment by Kirollos-Henry** [comment]
thanks for your reply.

I have already noticed that and I already did this before, but I have got an error that "python3-wheel-native" is not provided.

I think this is native in the other distributions or do you have any idea to add and build it.

Thank you in advance,

Best Regards,
Kirollos Henry

**Comment by NobuoTsukamoto** [comment]
Are you adding a `meta-python` layer?
e.g)
```
bitbake-layers add-layer _PATH_TO_/meta-openembedded/meta-python/
```

**Comment by KirollosTadros** [comment]
unfortunately it is already added.

layer                 path                                      priority
==========================================================================
meta-processor-sdk    /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-processor-sdk  15
meta-aws              /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-aws  6
meta-ros              /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-ros  7
meta-arago-distro     /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-arago/meta-arago-distro  10
meta-arago-extras     /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-arago/meta-arago-extras  10
meta-browser          /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-browser  7
meta-qt5              /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-qt5  7
meta-virtualization   /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-virtualization  8
meta-networking       /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-networking  5
meta-python           /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-python  7
meta-oe               /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-oe  6
meta-gnome            /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-gnome  7
meta-multimedia       /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-multimedia  6
meta-filesystems      /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-filesystems  6
meta-ti               /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-ti  6
meta-linaro-toolchain  /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-linaro/meta-linaro-toolchain  30
meta-optee            /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-linaro/meta-optee  8
meta                  /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/oe-core/meta  5
meta-custom           /home/ave-lap-99/processor-sdk-yocto/tisdk/meta-custom  6
meta-scipy            /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-scipy  6
meta-tensorflow-lite  /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-tensorflow-lite  6

**Comment by Kirollos-Henry** [comment]
unfortunately it is already added 

layer                 path                                      priorit

meta-processor-sdk    /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-processor-sdk  15
meta-aws              /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-aws  6
meta-ros              /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-ros  7
meta-arago-distro     /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-arago/meta-arago-distro  10
meta-arago-extras     /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-arago/meta-arago-extras  10
meta-browser          /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-browser  7
meta-qt5              /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-qt5  7
meta-virtualization   /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-virtualization  8
meta-networking       /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-networking  5
meta-python           /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-python  7
meta-oe               /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-oe  6
meta-gnome            /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-gnome  7
meta-multimedia       /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-multimedia  6
meta-filesystems      /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-openembedded/meta-filesystems  6
meta-ti               /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-ti  6
meta-linaro-toolchain  /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-linaro/meta-linaro-toolchain  30
meta-optee            /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-linaro/meta-optee  8
meta                  /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/oe-core/meta  5
meta-custom           /home/ave-lap-99/processor-sdk-yocto/tisdk/meta-custom  6
meta-scipy            /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-scipy  6
meta-tensorflow-lite  /home/ave-lap-99/processor-sdk-yocto/tisdk/sources/meta-tensorflow-lite  6

**Comment by Kirollos-Henry** [comment]
and off course there is no other way to build and install python3 tensor flow on yocto right?

**Comment by NobuoTsukamoto** [comment]
This is because there is no python3-wheel recipe in the thud branch of meta-openembedded (after warrior).
- https://layers.openembedded.org/layerindex/recipe/96041/

If possible, build with warrior or later.  
or You may be able to use python3-wheel-native in the meta-sca layer (I have never confirmed).
- https://layers.openembedded.org/layerindex/recipe/97136/
- https://github.com/priv-kweihmann/meta-sca

**Comment by Kirollos-Henry** [comment]
The problem that I am not using native yocto it is arago project a yocto project based on thud a product of Texas instruments for their hardware.

I will check with Texas instruments if there is way build different distro for the same board and I will also check the layer and recipes you mentioned.
I will check and try all this and update you.

Thank you so much for your help.

**Comment by ZuzooVn** [comment]
> The problem that I am not using native yocto it is arago project a yocto project based on thud a product of Texas instruments for their hardware.
> 
> I will check with Texas instruments if there is way build different distro for the same board and I will also check the layer and recipes you mentioned. I will check and try all this and update you.
> 
> Thank you so much for your help.

@Kirollos-Henry Did you find the solution?
